---
- hosts: Controller
  vars:
    metadata:
      name: MySQL Open Files Limit
      description: >
        Verify the `open-files-limit` configuration is high enough

        https://access.redhat.com/solutions/1598733
      groups:
        - post-deployment
    min_open_files_limit: 16384
  tasks:
  - name: Get the open_files_limit value
    become: true
    command: docker exec -u root -it mysql ulimit -n
    changed_when: False
    register: mysqld_open_files_limit
  - name: Test the open-files-limit value
    fail:
      msg: >
        The open_files_limit option for mysql must be higher than
        {{ min_open_files_limit }}. Right now it's {{ mysqld_open_files_limit.stdout }}.
    failed_when: "mysqld_open_files_limit.stdout|int < min_open_files_limit"
