---
metadata:
  name: Undercloud Neutron Sanity Check
  description: >
    Run `neutron-sanity-check` on the undercloud node to find out
    potential issues with Neutron's configuration.

    The tool expects all the configuration files that are passed
    to the Neutron services.
  groups:
    - pre-introspection
